// This file is automatically generated. Do not edit it directly.

import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";


// 🔐 Variáveis de ambiente

const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL;

const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;


// 🚨 Proteção contra erro silencioso (EVITA tela branca)

if (!SUPABASE_URL) {

  console.error(
    "❌ VITE_SUPABASE_URL não encontrada. Verifique o arquivo .env"
  );

  throw new Error(
    "Missing VITE_SUPABASE_URL"
  );

}

if (!SUPABASE_PUBLISHABLE_KEY) {

  console.error(
    "❌ VITE_SUPABASE_PUBLISHABLE_KEY não encontrada. Verifique o arquivo .env"
  );

  throw new Error(
    "Missing VITE_SUPABASE_PUBLISHABLE_KEY"
  );

}



// 🚀 Criação do cliente Supabase

export const supabase =
  createClient<Database>(
    SUPABASE_URL,
    SUPABASE_PUBLISHABLE_KEY,
    {
      auth: {

        storage: localStorage,

        persistSession: true,

        autoRefreshToken: true,

        detectSessionInUrl: true,

      },
    }
  );
